### PR TITLE
PROD-952 pip3 address in projects page setup needs to change

### PR DESCRIPTION
**Pull request by gseyffert-sync**
Giving this Action a try to auto-publish a `latest` version at the same time we publish updated documentation - https://github.com/EndBug/latest-tag

### CODE REVIEW

**Comment by gseyffert-sync** [comment]
I'm not sure how to test this prior to merging this PR 🤔

**Comment by gseyffert-sync** [comment]
An alternative we could use instead, which works for tags other than just `latest` - https://github.com/marketplace/actions/actions-tagger

**Review by rmoneys — COMMENTED** [review]
That's a cool workflow step: https://github.com/EndBug/latest-tag. I added it to the ticket: https://synccomputing.atlassian.net/browse/PROD-910

This doesn't guarantee that latest points to a release. Users might use it to download a revision between releases (tags) which could make it difficult to troubleshoot issues, e.g. `sync-cli --version` reports "0.0.2" but really they're running something from a couple commits after that. How about we manually set it until the above ticket is resolved (hopefully next sprint).

**Comment by gseyffert-sync** [comment]
yeah - I'm wondering if I should just look at `actions-tagger` and potentially just address the whole release "action" in this PR 🤔 if you don't mind me picking up that ticket

**Comment by rmoneys** [comment]
> yeah - I'm wondering if I should just look at actions-tagger and potentially just address the whole release "action" in this PR 🤔 if you don't mind me picking up that ticket

Please do!

**Pull request closed without merging**
