### PR TITLE
[PROD-1282] Add workspace config attributes and update API paths

### PR DESCRIPTION
**Pull request by rmoneys**
https://synccomputing.atlassian.net/browse/PROD-1282

### CODE REVIEW

**Review by brandon-kaplan — APPROVED** [review]
Approving because of the urgency, but as a follow up im wondering if we can get region from the unity catalog api's instead of getting it as input, since its static for the entire metastore

**Comment by rmoneys** [comment]
@brandon-kaplan, can you point me to the API?

**Comment by brandon-kaplan** [comment]
what if we used 
[Get metastore assignment for workspace](https://docs.databricks.com/api/workspace/metastores/current)
and then used that ID to [get metastore](https://docs.databricks.com/api/workspace/metastores/get) and used the region value from that? is that too many api calls and slowing things down?

**Comment by rmoneys** [comment]
No - seems like a surer way to get the correct region

**Comment by rmoneys** [comment]
FYI, started implementing this in the backend: https://github.com/synccomputingcode/sync_backend/pull/444/files#diff-afea6009de14705d2f7c045cedbde288336eeb6b118274adbf31462f52bf8a25

**Pull request merged**
